"""Inline the sources into one file that works when double-clicked.

Why this exists
---------------
The first cut of this app was `index.html` plus three sibling files loaded with
`<script type="module" src="…">`. It worked when served over http and was
completely inert from `file://` — Chromium refuses a module script fetched
from an opaque origin:

    Access to script at 'file:///…/app.js' from origin 'null' has been blocked
    by CORS policy

A browser test caught it. Nothing else would have: every casual check happens
through a dev server, and the failure is silent, a page that renders its own
markup and then does nothing at all.

That is not a cosmetic problem here. The recipient this app is for was handed a
package by a party they are in dispute with, and is as likely to be a claims
adjuster with a zip file as a developer with a terminal. "Run a web server
first" is infrastructure, and the argument for verifying in a browser was that
it needs none. So the deliverable is one file.

Inline `<script type="module">` is not fetched, so it is not subject to CORS
and runs from disk. The sources stay separate for reading and for the node
differential test; this stitches them together.

Run it after touching any source here:

    python webapp/build.py

`webapp-bundle-current` fails the build if you forget, the same way
`claims-ledger-current` guards `CLAIMS.md`.
"""
import base64
import hashlib
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent

# Order matters: app.js uses what the two before it define.
SOURCES = ("verify.js", "api.js", "app.js")

BANNER = """/* Generated by webapp/build.py from verify.js, api.js and app.js.
   Do not edit this file — edit those and re-run the builder. */"""


def strip_module_syntax(source: str) -> str:
    """Remove import/export keywords; one scope needs neither.

    Only the forms this codebase uses are handled, and anything unexpected
    raises rather than being silently passed through — a stray `import` left in
    an inline module is a syntax error that turns the whole page off, which is
    the failure this file exists to prevent.
    """
    out = []
    for line in source.splitlines():
        if re.match(r"^\s*import\s.*\sfrom\s+[\"'].+[\"'];\s*$", line):
            continue
        if re.match(r"^\s*import\s+[\"'].+[\"'];\s*$", line):
            continue
        if re.match(r"^\s*(export\s+default|export\s*\{)", line):
            raise ValueError(f"unsupported export form: {line.strip()!r}")
        out.append(re.sub(r"^(\s*)export\s+", r"\1", line))
    return "\n".join(out)


def csp_hash(block: str) -> str:
    """The CSP source expression for one inline block.

    Inlining the sources broke the page's own Content-Security-Policy, which
    said `script-src 'self'` and therefore refused the script now sitting
    inside the document. The lazy repair is `'unsafe-inline'`, which switches
    the protection off for every script the page will ever contain.

    Hashing is better than the thing it replaces. The policy now names the
    exact bytes it will execute, so the page refuses to run a script that is
    not the one built here — including an edit made to the file after it was
    handed to someone. For a document whose job is to be trusted by a stranger
    who received it from a party in a dispute, a page that will not run altered
    code is worth the extra line.
    """
    digest = hashlib.sha256(block.encode()).digest()
    return f"'sha256-{base64.b64encode(digest).decode()}'"


def build() -> str:
    page = (HERE / "page.html").read_text()
    css = (HERE / "styles.css").read_text()
    js = "\n\n".join(strip_module_syntax((HERE / name).read_text())
                     for name in SOURCES)

    style_block = f"\n{css}\n"
    script_block = f"\n{BANNER}\n\n{js}\n"

    for marker, replacement in (
        ("<!--SCRIPT-HASH-->", csp_hash(script_block)),
        ("<!--STYLE-HASH-->", csp_hash(style_block)),
        ("<!--STYLES-->", f"<style>{style_block}</style>"),
        ("<!--SCRIPT-->", f'<script type="module">{script_block}</script>'),
    ):
        if marker not in page:
            raise ValueError(f"{marker} missing from page.html")
        page = page.replace(marker, replacement)

    if "src=" in page or 'href="' in page.split("<style>")[0]:
        # A single file that still fetches something is not a single file, and
        # the CSP in the page forbids it anyway — better to fail here than to
        # ship a page that half works offline.
        raise ValueError("the bundle still references an external resource")
    return page


def main():
    target = HERE / "shield.html"
    target.write_text(build())
    print(f"wrote {target} ({target.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
